Warning: no key algorithms provided; JENKINS-42959 disabled
SSHLauncher{host='172.31.89.34', port=22, credentialsId='124a4cb9-ce5f-4c0a-9c92-88c2fc98eff2', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=60, maxNumRetries=10, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.KnownHostsFileKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[04/20/22 12:34:31] [SSH] Opening SSH connection to 172.31.89.34:22.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 10 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 9 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 8 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 7 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 6 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 5 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 4 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 3 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 2 more retries left.
No route to host (Host unreachable)
SSH Connection failed with IOException: "No route to host (Host unreachable)", retrying in 15 seconds. There are 1 more retries left.
No route to host (Host unreachable)
ERROR: Connection is not established!
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:988)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.getRemainingAuthMethods(TrileadSSHPublicKeyAuthenticator.java:89)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.canAuthenticate(TrileadSSHPublicKeyAuthenticator.java:81)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:222)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:173)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:885)
	at hudson.plugins.sshslaves.SSHLauncher.lambda$launch$0(SSHLauncher.java:434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[04/20/22 12:37:50] Launch failed - cleaning up connection
[04/20/22 12:37:50] [SSH] Connection closed.
